baseURL = "https://magnias.dev"
theme = "risotto"
title = "Magnias"
author = "Angelo Carly"
copyright = "© 2022 Angelo Carly"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Angelo Carly"
description = "Creative coder, Math, Computer Graphics"
logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/angelocarly"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "angelo.carly@proton.me"

[[params.socialLinks]]
icon = "fab fa-linkedin-in"
title = "linkedin"
url = "https://www.linkedin.com/in/angelocarly"

[[params.socialLinks]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/dodecatonic/"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
